[[chains]]
name = "ethereum"
scanner_base_url = "https://api.etherscan.io/api"
scanner_api_key = "<api-key>"
rpc_url = "<archive-node-rpc-url>"
tick_lens_address = "<uniswap-tick-lens-address (Optional)>"

[[chains]]
name = "arbitrum"
scanner_base_url = "https://api.arbiscan.io/api"
scanner_api_key = "<api-key>"
rpc_url = "<archive-node-rpc-url>"
tick_lens_address = "<uniswap-tick-lens-address (Optional)>"
