[[chains]]
name = "ethereum"
scanner_base_url = "https://api.etherscan.io/api"
scanner_api_key = "<api-key>"
rpc_url = "<archive-node-rpc-url>"

[[chains]]
name = "arbitrum"
scanner_base_url = "https://api.arbiscan.io/api"
scanner_api_key = "<api-key>"
rpc_url = "<archive-node-rpc-url>"